FROM node:20-alpine
WORKDIR /usr/src/app
COPY package*.json ./

RUN npm install

COPY . .

# El comando se ejecutará desde docker-compose para iniciar el servidor de desarrollo
CMD ["npm", "run", "dev"]

